name: cloudflare

on:
  workflow_dispatch:

jobs:
  cloudflare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy-fce
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.RFbp9MZmFN5dRLrSc-6dFvSO-9bOK_Km7zEaCAln }}
          workingDirectory: cloudflare
          secrets: |
            GTKK
        env:
          GTKK: ${{ secrets.GTKK }}
